[package]
name = "kyanite-core"
description = "The core library for the kyanite project"
authors = ["Kyanite Project <contact@kyanite.mov>"]
version = "1.0.0-alpha.1"
rust-version = "1.98.0"
edition = "2024"

readme = "README.md"
license = "GPL-3.0-or-later"
homepage = "https://kyanite.mov"
repository = "https://github.com/Akeoott/kyanite-core"

include = ["/src", "LICENSE", "README.md"]

keywords = ["system", "kernel", "hardware", "telemetry", "process-management"]
categories = ["os", "command-line-utilities", "hardware-support", "filesystem"]

[features]
default = []
full = ["telemetry"]
telemetry = []

[[example]]
name = "dump"
required-features = ["telemetry"]

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
rayon = "1.12.0"
